"""organizations and filings tables

Revision ID: a70a2257ea45
Revises: 
Create Date: 2026-08-28 21:11:34.865557

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a70a2257ea45'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ein', sa.String(length=9), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('ntee_code', sa.String(length=10), nullable=True),
    sa.Column('subsection', sa.String(length=5), nullable=True),
    sa.Column('ruling_year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_ein'), 'organizations', ['ein'], unique=True)
    op.create_index(op.f('ix_organizations_state'), 'organizations', ['state'], unique=False)
    op.create_table('filings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('tax_year', sa.Integer(), nullable=False),
    sa.Column('form_type', sa.String(length=10), nullable=True),
    sa.Column('total_revenue', sa.BigInteger(), nullable=True),
    sa.Column('total_expenses', sa.BigInteger(), nullable=True),
    sa.Column('total_assets', sa.BigInteger(), nullable=True),
    sa.Column('total_liabilities', sa.BigInteger(), nullable=True),
    sa.Column('contributions', sa.BigInteger(), nullable=True),
    sa.Column('program_revenue', sa.BigInteger(), nullable=True),
    sa.Column('program_expenses', sa.BigInteger(), nullable=True),
    sa.Column('admin_expenses', sa.BigInteger(), nullable=True),
    sa.Column('fundraising_expenses', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_filings_org_year', 'filings', ['organization_id', 'tax_year'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_filings_org_year', table_name='filings')
    op.drop_table('filings')
    op.drop_index(op.f('ix_organizations_state'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_ein'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
